# Generated by Django 4.0.4 on 2022-05-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
