# Generated by Django 4.0.4 on 2022-06-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_roomrepairs_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Branch',
            new_name='branch',
        ),
    ]
