# Generated by Django 4.0.4 on 2022-06-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_branch_student_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('N', 'None'), ('CS', 'Computer Science'), ('IS', 'Information Science'), ('EC', 'Electronics And Communication'), ('EEE', 'Electrical And Electronics'), ('ME', 'Mechanical')], default='N', max_length=4),
        ),
    ]
