# Generated by Django 4.0.4 on 2022-06-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_student_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='vacant',
            field=models.BooleanField(default=True),
        ),
    ]
