# Generated by Django 4.0.4 on 2022-06-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_medicine_medicinerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinerequest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
